spring.application.name=astazou
server.port=8080
server.forward-headers-strategy=framework
spring.servlet.multipart.max-file-size=100MB

# CORS
astazou.cors.allowed-origins=${ASTAZOU_CORS_ALLOWED_ORIGINS:*}

# AUTH
astazou.auth.session.expiration-time=${ASTAZOU_SESSION_EXPIRATION_TIME:3600}

# DATABASE
spring.datasource.url=jdbc:postgresql://${ASTAZOU_DATABASE_HOSTNAME:localhost}:${ASTAZOU_DATABASE_PORT:5432}/${ASTAZOU_DATABASE_NAME:astazou}
spring.datasource.username=${ASTAZOU_DATABASE_USERNAME:astazou}
spring.datasource.password=${ASTAZOU_DATABASE_PASSWORD:astazou}
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.data.jdbc.repositories.enabled=true
spring.datasource.hikari.maximum-pool-size=50

# Python environment
astazou.python.interpreter=${ASTAZOU_PYTHON_INTERPRETER:python3}
astazou.python.itau-pdf-parser=${ASTAZOU_ITAU_PDF_PARSER_SCRIPT:scripts/python/parse_itau_history_pdf.py}